### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst' 

### ISSUE THREAD

**Issue by mablue** [audreyfeldroy/design#11]
```cmd
pip install design --no-cache-dir        
Collecting design                                                          
  Downloading design-0.1.2.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mab\AppData\Local\Temp\pip-install-yv85l1j8\design_de25b7964
3d34be1b590f6ea13cc1d03\setup.py", line 19, in <module>
          history = open('HISTORY.rst', 'rt').read()
      FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'        
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with p
ip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by zersh01** [comment]
I have same error.

`$ pip3 install design 
Collecting design
  Using cached design-0.1.2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u18er1bz/design/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u18er1bz/design/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u18er1bz/design/pip-egg-info
         cwd: /tmp/pip-install-u18er1bz/design/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u18er1bz/design/setup.py", line 19, in <module>
        history = open('HISTORY.rst', 'rt').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by mablue** [comment]
i think its an unusefull demo script...that we use it as a dependency.
you need this for running which app?

**Comment by zersh01** [comment]
i found example, for python, where this module importing for create [simple gui](https://tproger.ru/translations/python-gui-pyqt/). 
And I cannot install that,by pip install... (or pip3)

How we can skip this error?
